version: "3.7"

# 2. TODO: would prefer on-failure restart_policy, but need to run this in script to look
# for if plugin exists first before reinstalling
# 3. TODO: would prefer this picks a driver version, and support driver updates

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "1m" 
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  plugin-rexray:
    <<: *default-opts
    image: mavenugo/swarm-exec:17.03.0-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - rexray_do_token
    environment:
      - REXRAY_DO_TOKEN_FILE=/run/secrets/rexray_do_token
    command: sh -c "docker plugin install --grant-all-permissions rexray/dobs DOBS_REGION=nyc3 DOBS_TOKEN=$$(cat $$REXRAY_DO_TOKEN_FILE) DOBS_CONVERTUNDERSCORES=true"
    deploy:
      mode: global
      restart_policy:
        condition: none

secrets:
  rexray_do_token:
    external: true
    name: rexray_do_token
